#!/bin/bash

echo "═══════════════════════════════════════════════"
echo "  📱 CALLOPS SMS - INCOMING MESSAGE MONITOR"
echo "═══════════════════════════════════════════════"
echo ""
echo "✅ Backend Server: Running on port 4000"
echo "✅ ngrok Tunnel: https://randi-osseous-winford.ngrok-free.dev"
echo "✅ Twilio Webhook: Configured"
echo ""
echo "═══════════════════════════════════════════════"
echo "  📥 HOW TO TEST"
echo "═══════════════════════════════════════════════"
echo ""
echo "From your phone (+447400409191),"
echo "send a text message to: +447458081879"
echo ""
echo "Try these commands:"
echo "  • 'help' - Get commands list"
echo "  • 'status' - Check account status"
echo "  • 'build a todo app' - Start building"
echo "  • Any text - Get echo response"
echo ""
echo "═══════════════════════════════════════════════"
echo "  👀 MONITORING OPTIONS"
echo "═══════════════════════════════════════════════"
echo ""
echo "Option 1: Watch this terminal (backend server logs)"
echo "Option 2: Open ngrok web UI: http://localhost:4040"
echo "Option 3: Check Twilio console"
echo ""
echo "Waiting for incoming messages..."
echo "Press Ctrl+C to stop monitoring"
echo ""
echo "═══════════════════════════════════════════════"
echo ""

# Watch the server logs for incoming SMS
tail -f /Users/harshalbhangale/.cursor/projects/Users-harshalbhangale-Desktop-Callops/terminals/806035.txt | grep --line-buffered -E "(📥|Incoming SMS|from:|body:)"
